### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by yorick-nhlstenden** [carlashley/tccprofile#2]
i got this error
macos monterey
12.0.1

tccprofile1 % ./tccprofile --scan
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/xxx/tccprofile1/./tccprofile/__main__.py", line 102, in <module>
  File "/Users/xxx/tccprofile1/./tccprofile/__main__.py", line 59, in main
  File "/Users/xxx/tccprofile1/./tccprofile/tcclib/tccdbscan.py", line 24, in user_managed
  File "/Users/xxx/tccprofile1/./tccprofile/tcclib/sqlitedb.py", line 48, in query
  File "/Users/xxx/tccprofile1/./tccprofile/tcclib/sqlitedb.py", line 36, in _connect
sqlite3.OperationalError: unable to open database file

**Comment by carlashley** [comment]
https://github.com/carlashley/tccprofile#usage

```To properly scan the TCC databases, full disk access may need to be provided to the relevant terminal application (for example, Terminal, iTerm, etc).```
